import 'package:flutter/material.dart';
import 'package:flutterapp/imssappapp/generatedpacientenoticia5widget/generated/GeneratedCongratsWidget13.dart';
import 'package:flutterapp/imssappapp/generatedpacientenoticia5widget/generated/GeneratedHeaderWidget15.dart';
import 'package:flutterapp/imssappapp/generatedpacientenoticia5widget/generated/GeneratedNotaWidget10.dart';
import 'package:flutterapp/imssappapp/generatedpacientenoticia5widget/generated/GeneratedBackWidget23.dart';

/* Frame paciente-noticia5
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPacientenoticia5Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 146.0,
                child: GeneratedHeaderWidget15(),
              ),
              Positioned(
                left: 20.0,
                top: 58.0,
                right: null,
                bottom: null,
                width: 340.0,
                height: 54.0,
                child: GeneratedCongratsWidget13(),
              ),
              Positioned(
                left: 20.0,
                top: 166.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 646.0,
                child: GeneratedNotaWidget10(),
              ),
              Positioned(
                left: 275.0,
                top: 712.0,
                right: null,
                bottom: null,
                width: 70.0,
                height: 70.0,
                child: GeneratedBackWidget23(),
              )
            ]),
      ),
    ));
  }
}
