import 'package:flutter/material.dart';
import 'package:flutterapp/imssappapp/generatedpacientenuevaconsultawidget/generated/GeneratedBackWidget.dart';
import 'package:flutterapp/imssappapp/generatedpacientenuevaconsultawidget/generated/GeneratedOKWidget.dart';
import 'package:flutterapp/imssappapp/generatedpacientenuevaconsultawidget/generated/GeneratedNuevaconsultaWidget2.dart';
import 'package:flutterapp/imssappapp/generatedpacientenuevaconsultawidget/generated/GeneratedSeparateWidget.dart';
import 'package:flutterapp/imssappapp/generatedpacientenuevaconsultawidget/generated/GeneratedPreguntasWidget.dart';

/* Frame paciente-nuevaconsulta
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPacientenuevaconsultaWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 39, 199, 110),
                ),
              ),
              Positioned(
                left: 58.0,
                top: 40.0,
                right: null,
                bottom: null,
                width: 261.0,
                height: 46.0,
                child: GeneratedNuevaconsultaWidget2(),
              ),
              Positioned(
                left: 20.0,
                top: 94.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 1.0,
                child: GeneratedSeparateWidget(),
              ),
              Positioned(
                left: 21.0,
                top: 104.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 656.0,
                child: GeneratedPreguntasWidget(),
              ),
              Positioned(
                left: 97.0,
                top: 712.416015625,
                right: null,
                bottom: null,
                width: 70.0,
                height: 69.708740234375,
                child: GeneratedBackWidget(),
              ),
              Positioned(
                left: 207.0,
                top: 712.416015625,
                right: null,
                bottom: null,
                width: 70.0,
                height: 69.708740234375,
                child: GeneratedOKWidget(),
              )
            ]),
      ),
    ));
  }
}
