import 'package:flutter/material.dart';
import 'package:flutter/foundation.dart' show kIsWeb;
import 'package:flutterapp/imssappapp/generatedbigbuttonwidget2/generated/GeneratedTextWidget14.dart';
import 'package:flutterapp/imssappapp/generatedbigbuttonwidget2/generated/GeneratedButtonWidget2.dart';

/* Component Big button
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedBigbuttonWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 335.0,
      height: 64.0,
      decoration: BoxDecoration(
        boxShadow: kIsWeb
            ? []
            : [
                BoxShadow(
                  color: Color.fromARGB(63, 0, 0, 0),
                  offset: Offset(0.0, 0.0),
                  blurRadius: 10.0,
                )
              ],
      ),
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 335.0,
              height: 64.0,
              child: GeneratedButtonWidget2(),
            ),
            Positioned(
              left: 0.0,
              top: 13.0,
              right: null,
              bottom: null,
              width: 340.0,
              height: 43.0,
              child: GeneratedTextWidget14(),
            )
          ]),
    ));
  }
}
