import 'package:flutter/material.dart';
import 'package:flutterapp/imssappapp/generatedpacienteusuarioaddwidget/generated/GeneratedToolbox4Widget1.dart';
import 'package:flutterapp/imssappapp/generatedpacienteusuarioaddwidget/generated/GeneratedNavbarWidget3.dart';
import 'package:flutterapp/imssappapp/generatedpacienteusuarioaddwidget/generated/GeneratedToolbox1Widget1.dart';
import 'package:flutterapp/imssappapp/generatedpacienteusuarioaddwidget/generated/GeneratedToolbox2Widget1.dart';
import 'package:flutterapp/imssappapp/generatedpacienteusuarioaddwidget/generated/GeneratedWelcomeWidget4.dart';
import 'package:flutterapp/imssappapp/generatedpacienteusuarioaddwidget/generated/GeneratedHerramientasWidget1.dart';
import 'package:flutterapp/imssappapp/generatedpacienteusuarioaddwidget/generated/GeneratedAddconsultaWidget1.dart';
import 'package:flutterapp/imssappapp/generatedpacienteusuarioaddwidget/generated/GeneratedToolbox3Widget1.dart';

/* Frame paciente-usuario-add
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPacienteusuarioaddWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 35.0,
                top: 40.0,
                right: null,
                bottom: null,
                width: 308.0,
                height: 46.0,
                child: GeneratedWelcomeWidget4(),
              ),
              Positioned(
                left: 104.0,
                top: 94.0,
                right: null,
                bottom: null,
                width: 172.0,
                height: 38.0,
                child: GeneratedHerramientasWidget1(),
              ),
              Positioned(
                left: 18.0,
                top: 140.0,
                right: null,
                bottom: null,
                width: 157.0,
                height: 250.0,
                child: GeneratedToolbox1Widget1(),
              ),
              Positioned(
                left: 193.0,
                top: 140.0,
                right: null,
                bottom: null,
                width: 157.0,
                height: 250.0,
                child: GeneratedToolbox2Widget1(),
              ),
              Positioned(
                left: 17.0,
                top: 410.0,
                right: null,
                bottom: null,
                width: 157.0,
                height: 250.0,
                child: GeneratedToolbox3Widget1(),
              ),
              Positioned(
                left: 194.0,
                top: 410.0,
                right: null,
                bottom: null,
                width: 157.0,
                height: 250.0,
                child: GeneratedToolbox4Widget1(),
              ),
              Positioned(
                left: 0.0,
                top: 697.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 115.0,
                child: GeneratedNavbarWidget3(),
              ),
              Positioned(
                left: 20.0,
                top: 652.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 111.0,
                child: GeneratedAddconsultaWidget1(),
              )
            ]),
      ),
    ));
  }
}
