import 'package:flutter/material.dart';
import 'package:flutterapp/imssappapp/generatedmedicousuarioaddwidget/generated/GeneratedToolbox1Widget3.dart';
import 'package:flutterapp/imssappapp/generatedmedicousuarioaddwidget/generated/GeneratedNavbarWidget7.dart';
import 'package:flutterapp/imssappapp/generatedmedicousuarioaddwidget/generated/GeneratedHerramientasWidget3.dart';
import 'package:flutterapp/imssappapp/generatedmedicousuarioaddwidget/generated/GeneratedToolbox2Widget3.dart';
import 'package:flutterapp/imssappapp/generatedmedicousuarioaddwidget/generated/GeneratedToolbox4Widget3.dart';
import 'package:flutterapp/imssappapp/generatedmedicousuarioaddwidget/generated/GeneratedToolbox3Widget3.dart';
import 'package:flutterapp/imssappapp/generatedmedicousuarioaddwidget/generated/GeneratedAddconsultaWidget3.dart';
import 'package:flutterapp/imssappapp/generatedmedicousuarioaddwidget/generated/GeneratedWelcomeWidget8.dart';

/* Frame medico-usuario-add
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedMedicousuarioaddWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 52.0,
                top: 40.0,
                right: null,
                bottom: null,
                width: 274.0,
                height: 46.0,
                child: GeneratedWelcomeWidget8(),
              ),
              Positioned(
                left: 104.0,
                top: 94.0,
                right: null,
                bottom: null,
                width: 172.0,
                height: 38.0,
                child: GeneratedHerramientasWidget3(),
              ),
              Positioned(
                left: 18.0,
                top: 140.0,
                right: null,
                bottom: null,
                width: 157.0,
                height: 250.0,
                child: GeneratedToolbox1Widget3(),
              ),
              Positioned(
                left: 193.0,
                top: 140.0,
                right: null,
                bottom: null,
                width: 157.0,
                height: 250.0,
                child: GeneratedToolbox2Widget3(),
              ),
              Positioned(
                left: 17.0,
                top: 410.0,
                right: null,
                bottom: null,
                width: 157.0,
                height: 250.0,
                child: GeneratedToolbox3Widget3(),
              ),
              Positioned(
                left: 194.0,
                top: 410.0,
                right: null,
                bottom: null,
                width: 157.0,
                height: 250.0,
                child: GeneratedToolbox4Widget3(),
              ),
              Positioned(
                left: 0.0,
                top: 697.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 115.0,
                child: GeneratedNavbarWidget7(),
              ),
              Positioned(
                left: 20.0,
                top: 652.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 111.0,
                child: GeneratedAddconsultaWidget3(),
              )
            ]),
      ),
    ));
  }
}
