import 'package:flutter/material.dart';
import 'package:flutterapp/imssappapp/generatedpacientemapawidget/generated/GeneratedInfoWidget18.dart';
import 'package:flutterapp/imssappapp/generatedpacientemapawidget/generated/GeneratedTitleWidget30.dart';
import 'package:flutterapp/imssappapp/generatedpacientemapawidget/generated/GeneratedMapWidget.dart';
import 'package:flutterapp/imssappapp/generatedpacientemapawidget/generated/GeneratedBackWidget5.dart';

/* Frame paciente-mapa
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPacientemapaWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 39, 199, 110),
                ),
              ),
              Positioned(
                left: 20.0,
                top: 30.0,
                right: null,
                bottom: null,
                width: 337.0,
                height: 90.0,
                child: GeneratedTitleWidget30(),
              ),
              Positioned(
                left: 31.0,
                top: 134.0,
                right: null,
                bottom: null,
                width: 315.0,
                height: 210.0,
                child: GeneratedMapWidget(),
              ),
              Positioned(
                left: 20.0,
                top: 354.0,
                right: null,
                bottom: null,
                width: 336.0,
                height: 267.0,
                child: GeneratedInfoWidget18(),
              ),
              Positioned(
                left: 153.0,
                top: 712.0,
                right: null,
                bottom: null,
                width: 70.0,
                height: 70.0,
                child: GeneratedBackWidget5(),
              )
            ]),
      ),
    ));
  }
}
