import 'package:flutter/material.dart';
import 'package:flutterapp/imssappapp/generatedmedicoconsultafinalwidget/generated/GeneratedGraciasporusarIMSSAppWidget1.dart';
import 'package:flutterapp/imssappapp/generatedmedicoconsultafinalwidget/generated/GeneratedLeinformaremosatupacientedeldiagnsticoSihasagendadounac.dart';
import 'package:flutterapp/imssappapp/generatedmedicoconsultafinalwidget/generated/GeneratedOKWidget6.dart';

/* Frame medico-consulta-final
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedMedicoconsultafinalWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Image.asset(
                  "assets/images/b7f5b6e611e68585f2e204f307c518de7f5f3a65.png",
                  color: null,
                  fit: BoxFit.cover,
                  width: 375.0,
                  height: 812.0,
                  colorBlendMode: BlendMode.dstATop,
                ),
              ),
              Positioned(
                left: 20.0,
                top: 222.0,
                right: null,
                bottom: null,
                width: 337.0,
                height: 116.0,
                child: GeneratedGraciasporusarIMSSAppWidget1(),
              ),
              Positioned(
                left: 20.0,
                top: 344.0,
                right: null,
                bottom: null,
                width: 337.0,
                height: 102.0,
                child:
                    GeneratedLeinformaremosatupacientedeldiagnsticoSihasagendadounac(),
              ),
              Positioned(
                left: 152.0,
                top: 712.0,
                right: null,
                bottom: null,
                width: 70.0,
                height: 69.708740234375,
                child: GeneratedOKWidget6(),
              )
            ]),
      ),
    ));
  }
}
