import 'package:flutter/material.dart';
import 'package:flutterapp/imssappapp/generatedpacientehistorialwidget/generated/GeneratedCongratsWidget1.dart';
import 'package:flutterapp/imssappapp/generatedpacientehistorialwidget/generated/GeneratedRecomendacionesWidget1.dart';
import 'package:flutterapp/imssappapp/generatedpacientehistorialwidget/generated/GeneratedHeaderWidget1.dart';
import 'package:flutterapp/imssappapp/generatedpacientehistorialwidget/generated/GeneratedBackWidget4.dart';

/* Frame paciente-historial
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPacientehistorialWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 146.0,
                child: GeneratedHeaderWidget1(),
              ),
              Positioned(
                left: 20.0,
                top: 58.0,
                right: null,
                bottom: null,
                width: 340.0,
                height: 54.0,
                child: GeneratedCongratsWidget1(),
              ),
              Positioned(
                left: 20.0,
                top: 166.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 646.0,
                child: GeneratedRecomendacionesWidget1(),
              ),
              Positioned(
                left: 275.0,
                top: 712.0,
                right: null,
                bottom: null,
                width: 70.0,
                height: 70.0,
                child: GeneratedBackWidget4(),
              )
            ]),
      ),
    ));
  }
}
