import 'package:flutter/material.dart';
import 'package:flutterapp/imssappapp/generatedpacientellamandowidget/generated/GeneratedTitleWidget28.dart';
import 'package:flutterapp/imssappapp/generatedpacientellamandowidget/generated/GeneratedCancelWidget.dart';
import 'package:flutterapp/imssappapp/generatedpacientellamandowidget/generated/GeneratedTitleWidget27.dart';

/* Frame paciente-llamando
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPacientellamandoWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Image.asset(
                  "assets/images/b7f5b6e611e68585f2e204f307c518de7f5f3a65.png",
                  color: null,
                  fit: BoxFit.cover,
                  width: 375.0,
                  height: 812.0,
                  colorBlendMode: BlendMode.dstATop,
                ),
              ),
              Positioned(
                left: 65.0,
                top: 247.0,
                right: null,
                bottom: null,
                width: 250.0,
                height: 62.0,
                child: GeneratedTitleWidget27(),
              ),
              Positioned(
                left: 107.0,
                top: 297.0,
                right: null,
                bottom: null,
                width: 163.0,
                height: 24.0,
                child: GeneratedTitleWidget28(),
              ),
              Positioned(
                left: 153.0,
                top: 682.0,
                right: null,
                bottom: null,
                width: 70.0,
                height: 70.0,
                child: GeneratedCancelWidget(),
              )
            ]),
      ),
    ));
  }
}
