import 'package:flutter/material.dart';
import 'package:flutterapp/imssappapp/generatedpacientecalculadorawidget/generated/GeneratedIngresesusdatosWidget.dart';
import 'package:flutterapp/imssappapp/generatedpacientecalculadorawidget/generated/GeneratedEstaturaWidget.dart';
import 'package:flutterapp/imssappapp/generatedpacientecalculadorawidget/generated/GeneratedPesoWidget.dart';
import 'package:flutterapp/imssappapp/generatedpacientecalculadorawidget/generated/GeneratedBackWidget2.dart';
import 'package:flutterapp/imssappapp/generatedpacientecalculadorawidget/generated/GeneratedOKWidget2.dart';
import 'package:flutterapp/imssappapp/generatedpacientecalculadorawidget/generated/GeneratedTitleWidget29.dart';

/* Frame paciente-calculadora
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPacientecalculadoraWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 98.0,
                top: 712.0,
                right: null,
                bottom: null,
                width: 70.0,
                height: 70.0,
                child: GeneratedBackWidget2(),
              ),
              Positioned(
                left: 208.0,
                top: 712.0,
                right: null,
                bottom: null,
                width: 70.0,
                height: 70.0,
                child: GeneratedOKWidget2(),
              ),
              Positioned(
                left: 34.0,
                top: 117.0,
                right: null,
                bottom: null,
                width: 310.0,
                height: 46.0,
                child: GeneratedTitleWidget29(),
              ),
              Positioned(
                left: 84.0,
                top: 161.0,
                right: null,
                bottom: null,
                width: 210.0,
                height: 35.0,
                child: GeneratedIngresesusdatosWidget(),
              ),
              Positioned(
                left: 20.0,
                top: 294.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 107.0,
                child: GeneratedEstaturaWidget(),
              ),
              Positioned(
                left: 20.0,
                top: 410.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 107.0,
                child: GeneratedPesoWidget(),
              )
            ]),
      ),
    ));
  }
}
