import 'package:flutter/material.dart';
import 'package:flutterapp/imssappapp/generatedpacientecontactarwidget/generated/GeneratedFrame1Widget.dart';
import 'package:flutterapp/imssappapp/generatedpacientecontactarwidget/generated/GeneratedBackWidget1.dart';
import 'package:flutterapp/imssappapp/generatedpacientecontactarwidget/generated/GeneratedTitleWidget26.dart';

/* Frame paciente-contactar
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPacientecontactarWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 107.0,
                top: 40.0,
                right: null,
                bottom: null,
                width: 167.0,
                height: 49.0,
                child: GeneratedTitleWidget26(),
              ),
              Positioned(
                left: 32.0,
                top: 84.0,
                right: null,
                bottom: null,
                width: 321.0,
                height: 728.0,
                child: GeneratedFrame1Widget(),
              ),
              Positioned(
                left: 153.0,
                top: 717.0,
                right: null,
                bottom: null,
                width: 70.0,
                height: 70.0,
                child: GeneratedBackWidget1(),
              )
            ]),
      ),
    ));
  }
}
