import 'package:flutter/material.dart';
import 'package:flutterapp/imssappapp/generatedmediconuevaconsultawidget/generated/GeneratedOKWidget3.dart';
import 'package:flutterapp/imssappapp/generatedmediconuevaconsultawidget/generated/GeneratedQuest1Widget1.dart';
import 'package:flutterapp/imssappapp/generatedmediconuevaconsultawidget/generated/GeneratedSeparateWidget3.dart';
import 'package:flutterapp/imssappapp/generatedmediconuevaconsultawidget/generated/GeneratedSeparateWidget2.dart';
import 'package:flutterapp/imssappapp/generatedmediconuevaconsultawidget/generated/GeneratedNuevaconsultaWidget5.dart';
import 'package:flutterapp/imssappapp/generatedmediconuevaconsultawidget/generated/GeneratedCheckWidget.dart';
import 'package:flutterapp/imssappapp/generatedmediconuevaconsultawidget/generated/GeneratedInfoWidget31.dart';
import 'package:flutterapp/imssappapp/generatedmediconuevaconsultawidget/generated/GeneratedBackWidget6.dart';

/* Frame medico-nuevaconsulta
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedMediconuevaconsultaWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 0, 142, 223),
                ),
              ),
              Positioned(
                left: 57.0,
                top: 157.0,
                right: null,
                bottom: null,
                width: 261.0,
                height: 46.0,
                child: GeneratedNuevaconsultaWidget5(),
              ),
              Positioned(
                left: 19.0,
                top: 211.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 1.0,
                child: GeneratedSeparateWidget2(),
              ),
              Positioned(
                left: 20.0,
                top: 221.0,
                right: null,
                bottom: null,
                width: 337.0,
                height: 191.0,
                child: GeneratedInfoWidget31(),
              ),
              Positioned(
                left: 20.0,
                top: 430.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 189.0,
                child: GeneratedQuest1Widget1(),
              ),
              Positioned(
                left: 20.0,
                top: 420.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 1.0,
                child: GeneratedSeparateWidget3(),
              ),
              Positioned(
                left: 30.0,
                top: 629.0,
                right: null,
                bottom: null,
                width: 217.0,
                height: 25.0,
                child: GeneratedCheckWidget(),
              ),
              Positioned(
                left: 97.0,
                top: 712.416015625,
                right: null,
                bottom: null,
                width: 70.0,
                height: 69.708740234375,
                child: GeneratedBackWidget6(),
              ),
              Positioned(
                left: 207.0,
                top: 712.416015625,
                right: null,
                bottom: null,
                width: 70.0,
                height: 69.708740234375,
                child: GeneratedOKWidget3(),
              )
            ]),
      ),
    ));
  }
}
