import 'package:flutter/material.dart';
import 'package:flutterapp/imssappapp/generatedfechawidget/generated/GeneratedBackWidget8.dart';
import 'package:flutterapp/imssappapp/generatedfechawidget/generated/GeneratedOKWidget5.dart';
import 'package:flutterapp/imssappapp/generatedfechawidget/generated/GeneratedInputWidget31.dart';
import 'package:flutterapp/imssappapp/generatedfechawidget/generated/GeneratedIngresalafechadetucitaWidget.dart';

/* Frame fecha
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFechaWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 0, 142, 223),
                ),
              ),
              Positioned(
                left: 20.0,
                top: 325.0,
                right: null,
                bottom: null,
                width: 337.0,
                height: 90.0,
                child: GeneratedIngresalafechadetucitaWidget(),
              ),
              Positioned(
                left: 20.0,
                top: 423.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 64.0,
                child: GeneratedInputWidget31(),
              ),
              Positioned(
                left: 97.0,
                top: 712.416015625,
                right: null,
                bottom: null,
                width: 70.0,
                height: 69.708740234375,
                child: GeneratedBackWidget8(),
              ),
              Positioned(
                left: 207.0,
                top: 712.416015625,
                right: null,
                bottom: null,
                width: 70.0,
                height: 69.708740234375,
                child: GeneratedOKWidget5(),
              )
            ]),
      ),
    ));
  }
}
