import 'package:flutter/material.dart';
import 'package:flutterapp/imssappapp/generatedinputwidget34/generated/GeneratedInputWidget36.dart';
import 'package:flutterapp/imssappapp/generatedinputwidget34/generated/GeneratedInputWidget35.dart';

/* Component Input
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedInputWidget34 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 335.0,
      height: 64.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 336.0,
              height: 65.0,
              child: GeneratedInputWidget35(),
            ),
            Positioned(
              left: 14.0,
              top: 19.0,
              right: null,
              bottom: null,
              width: 50.0,
              height: 30.0,
              child: GeneratedInputWidget36(),
            )
          ]),
    ));
  }
}
