import 'package:flutter/material.dart';
import 'package:flutterapp/imssappapp/generatedmedicousuariowidget/generated/GeneratedToolbox3Widget2.dart';
import 'package:flutterapp/imssappapp/generatedmedicousuariowidget/generated/GeneratedToolbox1Widget2.dart';
import 'package:flutterapp/imssappapp/generatedmedicousuariowidget/generated/GeneratedToolbox2Widget2.dart';
import 'package:flutterapp/imssappapp/generatedmedicousuariowidget/generated/GeneratedWelcomeWidget7.dart';
import 'package:flutterapp/imssappapp/generatedmedicousuariowidget/generated/GeneratedNavbarWidget6.dart';
import 'package:flutterapp/imssappapp/generatedmedicousuariowidget/generated/GeneratedHerramientasWidget2.dart';
import 'package:flutterapp/imssappapp/generatedmedicousuariowidget/generated/GeneratedToolbox4Widget2.dart';

/* Frame medico-usuario
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedMedicousuarioWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 52.0,
                top: 40.0,
                right: null,
                bottom: null,
                width: 274.0,
                height: 46.0,
                child: GeneratedWelcomeWidget7(),
              ),
              Positioned(
                left: 104.0,
                top: 94.0,
                right: null,
                bottom: null,
                width: 172.0,
                height: 38.0,
                child: GeneratedHerramientasWidget2(),
              ),
              Positioned(
                left: 18.0,
                top: 140.0,
                right: null,
                bottom: null,
                width: 157.0,
                height: 250.0,
                child: GeneratedToolbox1Widget2(),
              ),
              Positioned(
                left: 193.0,
                top: 140.0,
                right: null,
                bottom: null,
                width: 157.0,
                height: 250.0,
                child: GeneratedToolbox2Widget2(),
              ),
              Positioned(
                left: 17.0,
                top: 410.0,
                right: null,
                bottom: null,
                width: 157.0,
                height: 250.0,
                child: GeneratedToolbox3Widget2(),
              ),
              Positioned(
                left: 194.0,
                top: 410.0,
                right: null,
                bottom: null,
                width: 157.0,
                height: 250.0,
                child: GeneratedToolbox4Widget2(),
              ),
              Positioned(
                left: 0.0,
                top: 697.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 115.0,
                child: GeneratedNavbarWidget6(),
              )
            ]),
      ),
    ));
  }
}
