import 'package:flutter/material.dart';
import 'package:flutterapp/imssappapp/generatedpacienteiniciowidget/generated/GeneratedWelcomeWidget1.dart';
import 'package:flutterapp/imssappapp/generatedpacienteiniciowidget/generated/GeneratedNavbarWidget.dart';
import 'package:flutterapp/imssappapp/generatedpacienteiniciowidget/generated/GeneratedPostspacienteWidget1.dart';
import 'package:flutterapp/imssappapp/generatedpacienteiniciowidget/generated/GeneratedNoticiasWidget.dart';
import 'package:flutterapp/imssappapp/generatedpacienteiniciowidget/generated/GeneratedClosesessionWidget.dart';
import 'package:flutterapp/imssappapp/generatedpacienteiniciowidget/generated/GeneratedPostspacienteWidget.dart';

/* Frame paciente-inicio
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPacienteinicioWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: -1.0,
                top: 133.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 637.0,
                child: GeneratedPostspacienteWidget(),
              ),
              Positioned(
                left: -1.0,
                top: 133.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 637.0,
                child: GeneratedPostspacienteWidget1(),
              ),
              Positioned(
                left: 20.0,
                top: 40.0,
                right: null,
                bottom: null,
                width: 203.0,
                height: 49.0,
                child: GeneratedWelcomeWidget1(),
              ),
              Positioned(
                left: 141.0,
                top: 97.0,
                right: null,
                bottom: null,
                width: 104.0,
                height: 38.0,
                child: GeneratedNoticiasWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 697.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 115.0,
                child: GeneratedNavbarWidget(),
              ),
              Positioned(
                left: 302.0,
                top: 37.0,
                right: null,
                bottom: null,
                width: 50.0,
                height: 50.0,
                child: GeneratedClosesessionWidget(),
              )
            ]),
      ),
    ));
  }
}
