import 'package:flutter/material.dart';
import 'package:flutterapp/imssappapp/generatedmediconuevaconsultacbxwidget/generated/GeneratedOKWidget4.dart';
import 'package:flutterapp/imssappapp/generatedmediconuevaconsultacbxwidget/generated/GeneratedBackWidget7.dart';
import 'package:flutterapp/imssappapp/generatedmediconuevaconsultacbxwidget/generated/GeneratedQuest1Widget2.dart';
import 'package:flutterapp/imssappapp/generatedmediconuevaconsultacbxwidget/generated/GeneratedSeparateWidget4.dart';
import 'package:flutterapp/imssappapp/generatedmediconuevaconsultacbxwidget/generated/GeneratedInfoWidget32.dart';
import 'package:flutterapp/imssappapp/generatedmediconuevaconsultacbxwidget/generated/GeneratedSeparateWidget5.dart';
import 'package:flutterapp/imssappapp/generatedmediconuevaconsultacbxwidget/generated/GeneratedCheckWidget1.dart';
import 'package:flutterapp/imssappapp/generatedmediconuevaconsultacbxwidget/generated/GeneratedNuevaconsultaWidget6.dart';

/* Frame medico-nuevaconsulta-cbx
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedMediconuevaconsultacbxWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 0, 142, 223),
                ),
              ),
              Positioned(
                left: 57.0,
                top: 157.0,
                right: null,
                bottom: null,
                width: 261.0,
                height: 46.0,
                child: GeneratedNuevaconsultaWidget6(),
              ),
              Positioned(
                left: 19.0,
                top: 211.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 1.0,
                child: GeneratedSeparateWidget4(),
              ),
              Positioned(
                left: 20.0,
                top: 221.0,
                right: null,
                bottom: null,
                width: 337.0,
                height: 191.0,
                child: GeneratedInfoWidget32(),
              ),
              Positioned(
                left: 20.0,
                top: 430.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 189.0,
                child: GeneratedQuest1Widget2(),
              ),
              Positioned(
                left: 20.0,
                top: 420.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 1.0,
                child: GeneratedSeparateWidget5(),
              ),
              Positioned(
                left: 30.0,
                top: 629.0,
                right: null,
                bottom: null,
                width: 217.0,
                height: 25.0,
                child: GeneratedCheckWidget1(),
              ),
              Positioned(
                left: 97.0,
                top: 712.416015625,
                right: null,
                bottom: null,
                width: 70.0,
                height: 69.708740234375,
                child: GeneratedBackWidget7(),
              ),
              Positioned(
                left: 207.0,
                top: 712.416015625,
                right: null,
                bottom: null,
                width: 70.0,
                height: 69.708740234375,
                child: GeneratedOKWidget4(),
              )
            ]),
      ),
    ));
  }
}
