import 'package:flutter/material.dart';
import 'package:flutterapp/imssappapp/generatedaddconsultawidget4/generated/GeneratedAddtabWidget4.dart';
import 'package:flutterapp/imssappapp/generatedaddconsultawidget4/generated/GeneratedNuevaconsultaWidget7.dart';

/* Component add-consulta
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAddconsultaWidget4 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 335.0,
      height: 111.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 335.0,
              height: 111.0,
              child: GeneratedAddtabWidget4(),
            ),
            Positioned(
              left: 42.0,
              top: 12.0,
              right: null,
              bottom: null,
              width: 252.0,
              height: 46.0,
              child: GeneratedNuevaconsultaWidget7(),
            )
          ]),
    ));
  }
}
