import 'package:flutter/material.dart';
import 'package:flutterapp/imssappapp/generatedpacienteusuariowidget/generated/GeneratedHerramientasWidget.dart';
import 'package:flutterapp/imssappapp/generatedpacienteusuariowidget/generated/GeneratedToolbox4Widget.dart';
import 'package:flutterapp/imssappapp/generatedpacienteusuariowidget/generated/GeneratedWelcomeWidget3.dart';
import 'package:flutterapp/imssappapp/generatedpacienteusuariowidget/generated/GeneratedToolbox1Widget.dart';
import 'package:flutterapp/imssappapp/generatedpacienteusuariowidget/generated/GeneratedToolbox2Widget.dart';
import 'package:flutterapp/imssappapp/generatedpacienteusuariowidget/generated/GeneratedToolbox3Widget.dart';
import 'package:flutterapp/imssappapp/generatedpacienteusuariowidget/generated/GeneratedNavbarWidget2.dart';

/* Frame paciente-usuario
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPacienteusuarioWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 35.0,
                top: 40.0,
                right: null,
                bottom: null,
                width: 308.0,
                height: 46.0,
                child: GeneratedWelcomeWidget3(),
              ),
              Positioned(
                left: 104.0,
                top: 94.0,
                right: null,
                bottom: null,
                width: 172.0,
                height: 38.0,
                child: GeneratedHerramientasWidget(),
              ),
              Positioned(
                left: 18.0,
                top: 140.0,
                right: null,
                bottom: null,
                width: 157.0,
                height: 250.0,
                child: GeneratedToolbox1Widget(),
              ),
              Positioned(
                left: 193.0,
                top: 140.0,
                right: null,
                bottom: null,
                width: 157.0,
                height: 250.0,
                child: GeneratedToolbox2Widget(),
              ),
              Positioned(
                left: 17.0,
                top: 410.0,
                right: null,
                bottom: null,
                width: 157.0,
                height: 250.0,
                child: GeneratedToolbox3Widget(),
              ),
              Positioned(
                left: 194.0,
                top: 410.0,
                right: null,
                bottom: null,
                width: 157.0,
                height: 250.0,
                child: GeneratedToolbox4Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 697.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 115.0,
                child: GeneratedNavbarWidget2(),
              )
            ]),
      ),
    ));
  }
}
