import 'package:flutter/material.dart';
import 'package:flutterapp/imssappapp/generatedmedicosueldowidget/generated/GeneratedHeaderWidget3.dart';
import 'package:flutterapp/imssappapp/generatedmedicosueldowidget/generated/GeneratedTitleWidget52.dart';
import 'package:flutterapp/imssappapp/generatedmedicosueldowidget/generated/GeneratedHistorialWidget.dart';
import 'package:flutterapp/imssappapp/generatedmedicosueldowidget/generated/GeneratedAcumuladoenlacuentaWidget.dart';
import 'package:flutterapp/imssappapp/generatedmedicosueldowidget/generated/GeneratedBackWidget10.dart';

/* Frame medico-sueldo
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedMedicosueldoWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 180.0,
                child: GeneratedHeaderWidget3(),
              ),
              Positioned(
                left: 96.0,
                top: 63.0,
                right: null,
                bottom: null,
                width: 188.0,
                height: 59.0,
                child: GeneratedTitleWidget52(),
              ),
              Positioned(
                left: 20.0,
                top: 200.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 614.0,
                child: GeneratedHistorialWidget(),
              ),
              Positioned(
                left: 153.0,
                top: 717.0,
                right: null,
                bottom: null,
                width: 70.0,
                height: 70.0,
                child: GeneratedBackWidget10(),
              ),
              Positioned(
                left: 78.0,
                top: 127.0,
                right: null,
                bottom: null,
                width: 220.0,
                height: 27.0,
                child: GeneratedAcumuladoenlacuentaWidget(),
              )
            ]),
      ),
    ));
  }
}
