import 'package:flutter/material.dart';
import 'package:flutterapp/imssappapp/generatedmedicoayudafinalwidget/generated/GeneratedHasayudadoauncompaeroEnelIMSSnosenorgulleceapoyareltrab.dart';
import 'package:flutterapp/imssappapp/generatedmedicoayudafinalwidget/generated/GeneratedOKWidget8.dart';
import 'package:flutterapp/imssappapp/generatedmedicoayudafinalwidget/generated/GeneratedIMSSWidget1.dart';
import 'package:flutterapp/imssappapp/generatedmedicoayudafinalwidget/generated/GeneratedMuybienWidget.dart';

/* Frame medico-ayuda-final
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedMedicoayudafinalWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        decoration: BoxDecoration(
          gradient: LinearGradient(
            begin: Alignment(-1.0, 1.0),
            end: Alignment(0.9999999701976776, -0.9999999701976778),
            stops: [0.0, 1.0],
            colors: [
              Color.fromARGB(255, 0, 142, 223),
              Color.fromARGB(255, 120, 205, 255)
            ],
          ),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              Positioned(
                left: 20.0,
                top: 329.0,
                right: null,
                bottom: null,
                width: 337.0,
                height: 89.0,
                child: GeneratedMuybienWidget(),
              ),
              Positioned(
                left: 20.0,
                top: 416.0,
                right: null,
                bottom: null,
                width: 337.0,
                height: 134.0,
                child:
                    GeneratedHasayudadoauncompaeroEnelIMSSnosenorgulleceapoyareltrab(),
              ),
              Positioned(
                left: 152.0,
                top: 712.0,
                right: null,
                bottom: null,
                width: 70.0,
                height: 69.708740234375,
                child: GeneratedOKWidget8(),
              ),
              Positioned(
                left: 137.0,
                top: 100.0,
                right: null,
                bottom: null,
                width: 100.0,
                height: 126.31578826904297,
                child: GeneratedIMSSWidget1(),
              )
            ]),
      ),
    ));
  }
}
