import 'package:flutter/material.dart';
import 'package:flutterapp/imssappapp/generatedpacientecalculadoraresultadowidget/generated/GeneratedCongratsWidget.dart';
import 'package:flutterapp/imssappapp/generatedpacientecalculadoraresultadowidget/generated/GeneratedHeaderWidget.dart';
import 'package:flutterapp/imssappapp/generatedpacientecalculadoraresultadowidget/generated/GeneratedRecomendacionesWidget.dart';
import 'package:flutterapp/imssappapp/generatedpacientecalculadoraresultadowidget/generated/GeneratedBackWidget3.dart';
import 'package:flutterapp/imssappapp/generatedpacientecalculadoraresultadowidget/generated/GeneratedIMCWidget.dart';

/* Frame paciente-calculadora-resultado
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPacientecalculadoraresultadoWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 230.0,
                child: GeneratedHeaderWidget(),
              ),
              Positioned(
                left: 20.0,
                top: 40.0,
                right: null,
                bottom: null,
                width: 337.0,
                height: 35.0,
                child: GeneratedCongratsWidget(),
              ),
              Positioned(
                left: 96.0,
                top: 86.0,
                right: null,
                bottom: null,
                width: 189.0,
                height: 130.0,
                child: GeneratedIMCWidget(),
              ),
              Positioned(
                left: 20.0,
                top: 250.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 562.0,
                child: GeneratedRecomendacionesWidget(),
              ),
              Positioned(
                left: 275.0,
                top: 712.0,
                right: null,
                bottom: null,
                width: 70.0,
                height: 70.0,
                child: GeneratedBackWidget3(),
              )
            ]),
      ),
    ));
  }
}
